### ISSUE TITLE
Мой путь конвертируется, но с ошибками, в поле objectBoundingBox вместо координат некоторых - NaN

### ISSUE THREAD

**Issue by truechernyshov** [yoksel/relative-clip-path#1]
Пытаюсь конвертировать такой путь, но он получается срезанным
`M125.104.132H.132L.16 144.941c.867 0 1.438.26 1.924.545.487.286 1.031.74 1.79 1.212.654.387 1.515.367 1.515.367.841 0 1.412-.26 1.898-.546.487-.285 1.031-.739 1.79-1.211.654-.388 1.515-.367 1.515-.367.84 0 1.412.26 1.898.545.486.286 1.03.74 1.79 1.212.654.387 1.515.367 1.515.367.84 0 1.411-.26 1.898-.546.486-.285 1.03-.739 1.79-1.211.654-.388 1.514-.367 1.514-.367.841 0 1.412.26 1.898.545.487.286 1.031.74 1.79 1.212.654.387 1.515.367 1.515.367.84 0 1.412-.26 1.898-.546.487-.285 1.031-.739 1.79-1.211.654-.388 1.515-.367 1.515-.367.84 0 1.412.26 1.898.545.486.286 1.03.74 1.79 1.212.654.387 1.515.367 1.515.367.84 0 1.411-.26 1.898-.546.486-.285 1.03-.739 1.79-1.211.654-.388 1.514-.367 1.514-.367.841 0 1.412.26 1.898.545.487.286 1.031.74 1.79 1.212.654.387 1.515.367 1.515.367.84 0 1.412-.26 1.898-.546.487-.285 1.031-.739 1.79-1.211.654-.388 1.515-.367 1.515-.367.84 0 1.412.26 1.898.545.486.286 1.03.74 1.79 1.212.654.387 1.515.367 1.515.367.84 0 1.411-.26 1.898-.546.486-.285 1.03-.739 1.79-1.211.654-.388 1.514-.367 1.514-.367.841 0 1.412.26 1.898.545.487.286 1.031.74 1.79 1.212.654.387 1.515.367 1.515.367.84 0 1.412-.26 1.898-.546.487-.285 1.031-.739 1.79-1.211.654-.388 1.515-.367 1.515-.367.84 0 1.412.26 1.898.545.486.286 1.03.74 1.79 1.212.654.387 1.515.367 1.515.367.84 0 1.411-.26 1.898-.546.486-.285 1.03-.739 1.79-1.211.654-.388 1.54-.367 1.54-.367.868 0 1.44.26 1.925.545.487.286 1.031.74 1.79 1.212.654.387 1.515.367 1.515.367.841 0 1.412-.26 1.898-.546.487-.285 1.031-.739 1.79-1.211.654-.388 1.515-.367 1.515-.367.84 0 1.412.26 1.898.545.486.286 1.03.74 1.79 1.212.654.387 1.515.367 1.515.367.84 0 1.411-.26 1.898-.546.486-.285 1.03-.739 1.79-1.211.654-.388 1.514-.367 1.514-.367.841 0 1.412.26 1.898.545.487.286 1.031.74 1.79 1.212.654.387 1.515.367 1.515.367.841 0 1.412-.26 1.898-.546.487-.285 1.031-.739 1.79-1.211.654-.388 1.515-.367 1.515-.367.84 0 1.412.26 1.898.545.486.286 1.03.74 1.79 1.212.654.387 1.515.367 1.515.367.84 0 1.411-.26 1.898-.546.486-.285 1.03-.739 1.79-1.211.654-.388 1.514-.367 1.514-.367z`

**Comment by truechernyshov** [comment]
Это после svgomg такой путь, а если брать его сразу из inkscape - то работает с remove offset. Спасибо.

**Comment by yoksel** [comment]
Конвертер должен понимать все пути, включая минифицированные. Спасибо за репорт : )

**Comment by yoksel** [comment]
Попробуйте ещё раз

**Comment by truechernyshov** [comment]
Теперь всё чётко.
